language: php

php:
  - 7.0

notifications:
  emails:
    - tiagorosadacost@gmail.com
  on_success: always

cache:
  directories:
    - vendor

before_install:
  - sudo apt-get install curl
  - sudo curl -s https://getcomposer.org/installer | php
  - sudo mv composer.phar /usr/local/bin/composer
before_script:
  - composer install
script:
  - ./vendor/bin/phpunit